# Generated by Django 3.1 on 2021-03-04 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='tag',
        ),
    ]
